# Any changes
'🔵 Требуется проверка':
- changed-files:
  - any-glob-to-any-file:
    - '**'

# Changes to a .dmm or anything in the _map subfolder
'🗺 Мапинг':
- changed-files:
  - any-glob-to-any-file:
    - '**/*.dmm'
    - '_maps/**'

# Any .dmi changes
'🎨 Спрайты 🎨':
- changed-files:
  - any-glob-to-any-file:
    - '**/*.dmi'

# Any changes if not in modulare folder
'🪓 НЕ МОДУЛЬНО 🪓':
- changed-files:
  - any-glob-to-any-file:
    - '_maps/map_files/**'
    - '_maps/shuttles/**'
    - 'code/**'
    - 'icons/**'
    - 'sound/**'

# Any sounds changes
'🔊 Звуки 🔊':
- changed-files:
  - any-glob-to-any-file:
    - '**/*.aif'
    - '**/*.aiff'
    - '**/*.it'
    - '**/*.mid'
    - '**/*.midi'
    - '**/*.mod'
    - '**/*.mp3'
    - '**/*.ogg'
    - '**/*.oxm'
    - '**/*.raw'
    - '**/*.s3m'
    - '**/*.wma'
    - '**/*.wav'
    - '**/*.xm'

# Changes to the SQL subfolder
'📚 SQL 📚':
- changed-files:
  - any-glob-to-any-file:
    - 'SQL/**'

# Changes to the tgui subfolder
'💬 TGUI':
- changed-files:
  - any-glob-to-any-file:
    - 'tgui/**'

# Changes to the config subfolder
'🔮 Конфиги 🔮':
- changed-files:
  - any-glob-to-any-file:
    - 'config/**/*'
    - 'config/example/**/*'

# Changes to a .dm or anything in the code subfolder
'🧱 Код 🧱':
- changed-files:
  - any-glob-to-any-file:
    - '**/*.dm'

# Changes to the .Github subfolder
'🏭 Github 🏭':
- changed-files:
  - any-glob-to-any-file:
    - '.github/**'
    - '.github/**/*'
    - '.vscode/**/*'
    - 'docs/**/*'
    - 'scripts/**/*'
    - 'test/**/*'
    - 'tools/**/*'
    - '.codebeatignore'
    - '.codebeatsettings'
    - '.editorconfig'
    - '.git*'
    - 'biome.json'
    - 'libmysql.dll'
    - 'LICENSE'
    - 'README.md'
    - 'SpacemanDMM.toml'
